%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm
%% Source: /net/isildur/ldisk/daily_build/18_prebuild_opu_o.2016-03-14_21/otp_src_18/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_HRL).
-define(COSEVENTCOMM_HRL, true).


-record('CosEventComm_Disconnected', {'OE_ID'="IDL:omg.org/CosEventComm/Disconnected:1.0"}).


-endif.


