%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventComm_PullerS
%% Source: /net/isildur/ldisk/daily_build/18_prebuild_opu_o.2016-03-14_21/otp_src_18/lib/cosEvent/src/cosEventApp.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTCOMM_PULLERS_HRL).
-define(OE_COSEVENTCOMM_PULLERS_HRL, true).




-endif.


