%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTime
%% Source: /net/isildur/ldisk/daily_build/18_prebuild_opu_o.2016-03-14_21/otp_src_18/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIME_HRL).
-define(COSTIME_HRL, true).


-record('CosTime_TimeUnavailable', {'OE_ID'="IDL:omg.org/CosTime/TimeUnavailable:1.0"}).


-endif.


