%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_EventChannelFactory
%% Source: /net/isildur/ldisk/daily_build/18_prebuild_opu_o.2016-03-14_21/otp_src_18/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_EVENTCHANNELFACTORY_HRL).
-define(COSNOTIFYCHANNELADMIN_EVENTCHANNELFACTORY_HRL, true).




-endif.


