%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNaming_BindingIterator
%% Source: /net/isildur/ldisk/daily_build/18_prebuild_opu_o.2016-03-14_21/otp_src_18/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNAMING_BINDINGITERATOR_HRL).
-define(COSNAMING_BINDINGITERATOR_HRL, true).




-endif.


