%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: erlang
%% Source: /net/isildur/ldisk/daily_build/18_prebuild_opu_o.2016-03-14_21/otp_src_18/lib/ic/include/erlang.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ERLANG_HRL).
-define(ERLANG_HRL, true).


-record(erlang_pid, {node, num, serial, creation}).
-record(erlang_port, {node, id, creation}).
-record(erlang_ref, {node, id, creation}).


-endif.


