%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventDomainAdmin_DomainNotFound
%% Source: /net/isildur/ldisk/daily_build/18_prebuild_opu_o.2016-03-14_21/otp_src_18/lib/cosEventDomain/src/CosEventDomainAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventDomainAdmin_DomainNotFound').
-ic_compiled("4_4").


-include("CosEventDomainAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosEventDomainAdmin/DomainNotFound:1.0",
                   "DomainNotFound",[]}.

%% returns id
id() -> "IDL:omg.org/CosEventDomainAdmin/DomainNotFound:1.0".

%% returns name
name() -> "CosEventDomainAdmin_DomainNotFound".



